name: scipy paper
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  issues: write
  pull-requests: read
jobs:
  preview:
    # Skip this action if we are not in a "paper" pull request
    if: contains(github.event.pull_request.labels.*.name, 'paper')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install MyST Markdown
        run: npm install -g mystmd
      - name: Install Typst for PDF builds
        uses: typst-community/setup-typst@v3
      - run: myst build --typst
        working-directory: papers/david_calhas
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Build Results
      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Build Results
      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            Build Results -- updated!
          reactions: rocket
  check:
    # Skip this action if we are not in a "paper" pull request
    if: contains(github.event.pull_request.labels.*.name, 'paper')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install MyST Markdown
        run: npm install -g curvenote
      - run: curvenote check
        working-directory: papers/david_calhas
